#!/bin/bash

set -e

mydir="$(dirname "${BASH_SOURCE[0]}")"
target_dir="${1:-$mydir}"

url=https://raw.githubusercontent.com/implicitconversions/git-subtree-fast/main


# need to download the updater first in case it updates itself.
# use bash exec to to do so, to avoid bash blowing up if the file changed.
(( INSTALL_IS_SECOND_RUN )) || {
    echo "Performing self-update step..."
    exec bash -c "curl $url/fetch-subtree-tools -o '$target_dir/fetch-subtree-tools' && export INSTALL_IS_SECOND_RUN=1 && '${BASH_SOURCE[0]}'"
}

echo "Fetching scripts into $(realpath "$target_dir")"

set -x
curl -o "$target_dir/subtree-add" $url/subtree-add
curl -o "$target_dir/subtree-pull" $url/subtree-pull
curl -o "$target_dir/subtree-push" $url/subtree-push
curl -o "$target_dir/git-subtree-fast" $url/git-subtree-fast

echo "Fetch of subtree commands completed successfully."
