#!/bin/bash

POSITIONAL=()
for item; do
    (( end_of_args  )) && POSITIONAL+=("$item") && continue
    [[ $item ]] || continue

    rval=${item#*=}
    case "$lval" in
        --help)         SHOW_HELP=1 ;;
        --)             end_of_args=1 ;;
        -*)             SUBTREE_ARGS+=("$item")  ;; # pass through to sub-command.
        *)              POSITIONAL+=( "$item" )
    esac
done

set -- "${POSITIONAL[@]}"

# this tool expects two positional arguments, followed by an optional third which can be a branch name.
# if not provided, then use the default branch name provided by the optional wrapper script.

(( $# < 3 )) && {
    set -- "${POSITIONAL[@]}" $DEFAULT_BRANCH
}

(( SHOW_HELP )) && {
    cat << BOOKENDS
usage: git-subtree-push SUBTREE_PREFIX UPSTREAM_URL BRANCH_NAME

Executes a subtree push for the git subdirectory SUBTREE_PREFIX. This directory must be relative to
the git toplevel directory. All three arguments are required.
BOOKENDS
    exit
}

subtree_prefix=$1
shift || {
    echo "$(basename $0): not enough arguments."
    exit
}

git_dir="$(git rev-parse --show-toplevel)" || {
    echo "$(basename "$0") must be called from a valid git workspace."
    exit 1
} >&2

cd "$git_dir" || exit
set -x
git-subtree-fast push --prefix "${SUBTREE_ARGS[@]}" $subtree_prefix "$@"
