#!/bin/bash

for item; do
    [[ $item == --help ]] && SHOW_HELP=1 && continue;
done

(( SHOW_HELP )) && {
    cat << BOOKENDS
usage: push.sh DIRNAME [BRANCH_NAME]
Executes a subtree push for DIRNAME. Uses information in subtree-config.txt to know
where to push to.

BOOKENDS
    exit
}

mydir=$(dirname ${BASH_SOURCE[0]})

subtree_dir=${1%/}
branch=${2:-masticore/subtree-push}
item=$(grep "^$subtree_dir " $mydir/subtree-config.txt)

shift 2 || shift

[[ $subtree_dir ]] || {
    >&2 echo "expected at least one argument. try --help for usage."
    exit 1
}

[[ $item ]] || {
    >&2 echo "error: no entry for '$subtree_dir' in $mydir/subtree-config.txt"
    exit 1
}

function subtree_exec() {
    set -x
    $mydir/git-subtree-fast.sh push --prefix "$@"
    { set +x; } &> /dev/null
}

subtree_exec $item $branch "$@"
